name: JFrog CLI OICD integration
on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write  # This is required for requesting the OIDC token
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: CheckOut
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://soleng.jfrog.io/ # JFrog platform url (for example: https://acme.jfrog.io)
      with:
        oidc-provider-name: github-oidc015
        oidc-audience: jfrog-github
        
    - name: Run JFrog CLI
      working-directory: maven-examples/maven-example
      run: |
        jf c show
        jf mvnc \
          --server-id-deploy setup-jfrog-cli-server \
          --server-id-resolve setup-jfrog-cli-server \
          --repo-deploy-releases test1-maven \
          --repo-deploy-snapshots test1-maven \
          --repo-resolve-releases test1-maven \
          --repo-resolve-snapshots test1-maven \
          --use-wrapper=true
          
        jf mvn clean install --build-name test-github-maven --build-number ${{github.run_number}}
        jf rt bce test-github-maven ${{github.run_number}}
        jf rt bag test-github-maven ${{github.run_number}}
        jf rt bp test-github-maven ${{github.run_number}}
