# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckOut
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up Maven 3.8.8
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
        tar -xzf apache-maven-3.8.8-bin.tar.gz
        echo "$(pwd)/apache-maven-3.8.8/bin" >> $GITHUB_PATH
        
    - name: Build with Maven
      run: |
        mvn -v 
        mvn -B package --file maven-examples/maven-example/pom.xml
        
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: https://soleng.jfrog.io/
      with:
        oidc-provider-name: github-oidc015
        oidc-audience: jfrog-github
    - name: Run JFrog CLI
      working-directory: maven-examples/maven-example
      run: |
        jf rt ping # Ping the server
        jf c show
        jf mvnc \
          --server-id-deploy setup-jfrog-cli-server \
          --server-id-resolve setup-jfrog-cli-server \
          --repo-deploy-releases test1-maven \
          --repo-deploy-snapshots test1-maven \
          --repo-resolve-releases test1-maven \
          --repo-resolve-snapshots test1-maven
          
        jf mvn clean install -Dmaven.version=3.8.8ã€€--build-name test-github-maven --build-number ${{github.run_number}}
        jf rt bce test-github-maven ${{github.run_number}}
        jf rt bag test-github-maven ${{github.run_number}}
        jf rt bp test-github-maven ${{github.run_number}}
